---
title: "Multivariate Analysis Project"
output: html_document
date: "2023-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = "Multivariate-Analysis-Project")
library(tidyverse)
library(factoextra)
library(fpc)
library(NbClust)
library(psych)
library(GPArotation)
library(MASS)
library(HSAUR2)
library(tidyquant)
library(expm)
library(vegan)
library(ca)

data <- read.csv("data.csv")
houseIncome <- data[,4]
data[,4] <- as.numeric( sub(",", "", houseIncome, fixed = TRUE))
row.names(data) <- data[,1]
data <- subset(data, select = -State)
```

```{r}
data_num <- data %>% select_if(is.numeric)
data_dist <- dist(data_num)
data_eclust <- eclust(data_num, "kmeans", 2)
data_silhouette <- fviz_silhouette(data_eclust)
data_clus <- data %>% 
  mutate(cluster = data_eclust$cluster, 
         vote_numeric = (data$Vote) %>% as_factor() %>% as.numeric())
data_stats <- cluster.stats(data_dist, data_clus$vote_numeric, data_clus$cluster)
data_vi <- data_stats$vi
data_rand <- data_stats$corrected.rand
table(data$State, data_eclust$cluster)
```

```{r}
data_num <- data %>% select_if(is.numeric)
numFactors <- fa.parallel(data_num, fm = "minres", fa = "fa")
twoFactor <- fa(data_num, nfactors = 2, rotate = "oblimin", fm = "minres")
print(twoFactor$loadings, cutoff = 0.3)
fa.diagram(twoFactor)
threeFactor <- fa(data_num, nfactors = 3, rotate = "oblimin", fm = "minres")
print(threeFactor$loadings, cutoff = 0.3)
fa.diagram(threeFactor)
```

```{r}
# data_dist <- dist(data)
# data_fit <- cmdscale(data_dist, eig = TRUE, k = 2)
# x <- data_fit$points[,1]
# y <- data_fit$points[,2]
# 
# plot(x, y, xlab = "Coordinate 1", ylab = "Coordinate 2",
#      main = "Multidimensional Scaling Results", type = "n")
# text(x, y, labels = row.names(data))


data_MDS <- metaMDS(data[,2:11], distance = "gower")

stressplot(data_MDS)

data_MDS$stress

data_2D_df <- data_MDS$points %>%
  as_tibble(rownames = "States")
colorVector <- c("blue", "red")
stateColorVector <- c()
for (i in data$Vote)  {
  if (i == "Democratic") {
    stateColorVector <- rbind(stateColorVector, "blue")
  }
  else {
    stateColorVector <- rbind(stateColorVector, "red")
  }
}
data_2D_df %>%
  ggplot(mapping = aes(x = MDS1, y = MDS2, color = stateColorVector)) +
  scale_colour_manual(values=colorVector) +
  geom_text(label = rownames(data), size = 2) +
  labs(x = "Dimension 1",
       y = "Dimension 2",
       title = "NMDS 2-D representation of Voting Dataset")
```